eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
